create table inputt
(
    id int generated by default as identity primary key,
    giorno date,
    ore time,
    quantita float
);
create table alimento
(
    id int generated by default as identity primary key,
    descrizione char(50),
    calorie int,
    idInput int,
    foreign key(idInput) references inputt(id)
);
create table allenamento
(
    id int generated by default as identity primary key,
    inizio time,
    fine time,
    pesoI float,
    pesoF float,
    avambraccioI float,
    avambraccioF float,
    cosciaI float,
    cosciaF float,
    giorno date
);
create table outputt
(
    id int generated by default as identity primary key,
    ore time,
    tipo char(20),
    quantita float,
    giorno date
);
create table persona
(
    id int generated by default as identity primary key,
    nome char(20) not null,
    cognome char(25) not null,
    dataNascita date,
    peso float,
    idInput int,
    idAllenamento int,
    idOutput int,
    foreign key(idInput) references inputt(id),
    foreign key(idAllenamento) references allenamento(id),
    foreign key(idOutput) references outputt(id)
);